CREATE TABLE USER (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL, 
    password VARCHAR(50) NOT NULL,      
    email VARCHAR(100) UNIQUE NOT NULL,
    date_of_birth DATE,                
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE CHAT_HISTORY (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NULL, 
    question VARCHAR(2000) NULL,      
    answer VARCHAR(4000) NULL,
	confidence_score DECIMAL(10, 5),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);